version: '3'
services:
  db:
    image: library/postgres:12.2
    env_file: env
    volumes:
      - postgress-data:/var/lib/postgresql/data
    stop_grace_period: 1m
  web:
    image: $OIOIOI_VERSION
    command: ["/sio2/oioioi/oioioi_init_prod.sh"]
    env_file: env
    ports:
      - "80:8000"
    volumes:
      - ./basic_settings.py:/sio2/deployment/basic_settings.py
      - filetracker:/sio2/deployment/media
    stop_grace_period: 3m
    depends_on:
      - db
      - broker
  worker:
    image: $OIOIOI_VERSION
    command: ["/sio2/oioioi/worker_init_prod.sh"]
    environment:
      WORKER_CONCURRENCY: 3
    stop_grace_period: 1m
    security_opt:
      - seccomp:./seccomp.json
    cap_add:
      - ALL
    depends_on:
      - db
  broker:
    image: library/rabbitmq:3.8
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_LOGS:
      RABBITMQ_SASL_LOGS:
    stop_grace_period: 1m
volumes:
  postgress-data:
  filetracker:
