version: '3.8'
services:
  db:
    image: library/postgres:15.1
    env_file: env
    volumes:
      - postgress-data:/var/lib/postgresql/data
    stop_grace_period: 1m
  web:
    image: $OIOIOI_VERSION
    command: ["/sio2/oioioi/oioioi_init.sh"]
    env_file: env
    environment:
      OIOIOI_SERVER_MODE: "uwsgi-http" # For nginx change this to "uwsgi"
    ports:
      - "80:80" # Expose 8000 for nginx
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./basic_settings.py:/sio2/deployment/basic_settings.py
      - filetracker:/sio2/deployment/media
    stop_grace_period: 3m
    depends_on:
      - db
      - broker
  worker:
    image: $OIOIOI_VERSION
    command: ["/sio2/oioioi/worker_init.sh"]
    environment:
      WORKER_CONCURRENCY: ${OIOIOI_CONCURRENCY}
      WORKER_RAM_MB: ${OIOIOI_RAM}
    stop_grace_period: 1m
    security_opt:
      - seccomp:./extra/docker/seccomp.json
      - apparmor:unconfined
    cap_add:
      - ALL
    depends_on:
      - db
  broker:
    image: library/rabbitmq:3.8
    volumes:
      - ./extra/docker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_LOGS:
      RABBITMQ_SASL_LOGS:
    stop_grace_period: 1m
volumes:
  postgress-data:
  filetracker:
