# Generated by Django 4.2.5 on 2023-11-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_merge_20230615_1827'),
        ('talent', '0004_alter_talentregistration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentParentContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_parent_contest', to='contests.contest', verbose_name='contest')),
                ('parent_contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='parent contest')),
            ],
            options={
                'verbose_name': 'Parent contest',
            },
        ),
    ]
