# Generated by Django 4.2.5 on 2023-11-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_talentparentcontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentregistration',
            name='room',
            field=models.CharField(max_length=15, null=True, verbose_name='Room number or name'),
        ),
    ]
