# Generated by Django 4.2.9 on 2024-01-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_filesmessage_submissionsmessage_submitmessage'),
        ('contests', '0017_merge_20230615_1827'),
    ]

    operations = [
    ]
