# Generated by Django 4.2.13 on 2024-06-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_contest_show_contest_rules'),
        ('contests', '0018_merge_20240128_1744'),
    ]

    operations = [
    ]
