# Generated by Django 4.2.23 on 2025-06-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_merge_20240616_1133'),
        ('contests', '0021_sync_indexes_state'),
    ]

    operations = [
    ]
